### ISSUE TITLE
Please add 'how to run' manual

### ISSUE THREAD

**Issue by NikitaEgorov** [RdJNL/TextTemplatingCore#1]
Please add 'how to run' manual

**Comment by danielmeza** [comment]
Press right click on the .tt file and then select Run Custom Tool 
![image](https://user-images.githubusercontent.com/16217470/97519752-bd1c3380-1967-11eb-84a0-8981f726adb8.png)

**Comment by RdJNL** [comment]
I'm sorry I didn't reply earlier, my e-mail notifications were turned off, apparently. A description of how to use it is in the readme on the main page of this repo. [Direct link](https://github.com/RdJNL/TextTemplatingCore#how-to-use-it)
