### ISSUE TITLE
Cannot generate the output in .Net6 VS 2022

### ISSUE THREAD

**Issue by mgh9** [RdJNL/TextTemplatingCore#10]
Hi, I'm using the extension in VS 2022 .Net 6 and got the following error:
![Screenshot 2022-05-21 214702](https://user-images.githubusercontent.com/56910329/169662438-34d55684-edfe-4879-a6ca-bb23ad517184.png)

Does it support .Net6 or not yet?

btw good job

**Comment by RdJNL** [comment]
Yes, it does support .NET 6 (if you have version 1.2.0). Your code throws an exception, but I can't tell why that happens without seeing the code.

**Comment by mgh9** [comment]
Ok that's my bad, sorry, that was a typo in my T4 template. It's like the hell without intellisense.

**Comment by RdJNL** [comment]
I agree. You could try VS Code, it's a bit better with T4 templates.
