### ISSUE TITLE
Support for dotnet 7/8

### ISSUE THREAD

**Issue by SergeyFilippov** [RdJNL/TextTemplatingCore#13]
Would be nice to have a support for dotnet 7 and 8 for this extension since MS doesn't seem to care about fixing templating for VS.

Are there any plans on adding the support for mentioned, especially since dotnet 8 is LTS?

For a time, I have my fork with net7 implemented, but not sure if you need a pull request from it.
Thanks for great work and very useful extension.

**Comment by RdJNL** [comment]
Yes, I'm planning to add .NET 8 support, I just need to make some time for that. I think there's a command line tool now included with Visual Studio that supports newer .NET versions. I hope eventually that will replace my tool.

**Comment by RdJNL** [comment]
Version 1.3.0 is out now with support for .NET 8.
