### ISSUE TITLE
Assembly System.Text.Json is starting to making troubles

### ISSUE THREAD

**Issue by ByteCraftServices** [RdJNL/TextTemplatingCore#2]
Hi,

As I noticed today, the latest VS Update seems to mess up the used assemblies.

Following error is displayed now, when I try to run the custom tool.
_Something went wrong executing the template in .NET Core: Error:
  An assembly specified in the application dependencies manifest (TemplateExecute.deps.json) was not found:
    package: 'System.Text.Json', version: '4.7.1'
    path: 'lib/netcoreapp3.0/System.Text.Json.dll'_

Currently this problem appeared on Microsoft Visual Studio Professional 2019
Version **16.8.3**

As i found int the release notes [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.8.3)
".NET 5.0.1 insertion into Visual Studio v 16.8.3" was included in the last update.

So this could be a potential reason.

Edit: I'm using it with .net Core 3.1 ;-)

**Comment by RdJNL** [comment]
That's strange, I'm also using VS 16.8.3 and it's working fine for me. Are you using the VS extension or are you using the command line tool? (Or is it happening with both?)

**Comment by ByteCraftServices** [comment]
Indeed. I'm using the VS extension. After updating the version number of System.Text.Json  in TemplateExecute.deps.json I can transform the template again

**Comment by RdJNL** [comment]
I've updated some packages and the dependency on System.Text.Json is gone in [version 1.1.0](https://github.com/RdJNL/TextTemplatingCore/releases/tag/v1.1.0).
