### ISSUE TITLE
.NET 5 Version

### ISSUE THREAD

**Issue by Jothay** [RdJNL/TextTemplatingCore#3]
Can you release a .NET 5 version? I get errors trying to load a .NET 5 dll into it from System.Runtime

**Comment by RdJNL** [comment]
I'm not sure when I have time, but I'll try to create an updated version soon.

**Comment by RdJNL** [comment]
.NET 5 support is here!

[Version 1.1.0](https://github.com/RdJNL/TextTemplatingCore/releases/tag/v1.1.0)

**Comment by Jothay** [comment]
@RdJNL Thank you so much for making this release!
