### ISSUE TITLE
Support For $(TargetPath)

### ISSUE THREAD

**Issue by mshsayem** [RdJNL/TextTemplatingCore#4]
For now it is only supporting` $(SolutionDir)` and `$(ProjectDir)`. It will be great to have support for `$(TargetPath)`.

**Comment by RdJNL** [comment]
What do you need that for? Do you want to use `$(TargetPath)` in an assembly directive?

**Comment by RdJNL** [comment]
Added in [version 1.1.0](https://github.com/RdJNL/TextTemplatingCore/releases/tag/v1.1.0)
